### ISSUE TITLE
unused Travis CI setup?

### ISSUE THREAD

**Issue by DanielRuf** [pnpm/spec#2]
It seems there is Travis CI enabled but not used  further configured?

https://travis-ci.com/pnpm/spec/builds/73894871

**Comment by zkochan** [comment]
it is not needed but there is no option to exclude repos from travis if is turned on for an org, so I just deactivated the auto builds

**Comment by DanielRuf** [comment]
Ah ok, I thought there was some setting to exclude singe repos and not enable it for all at once.

**Comment by zkochan** [comment]
yes, it is possible but it is easier just to select the "All repositories" radio instead of adding all separately
